name: drivepay
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.5.4+3
  http: ^1.3.0
  flutter_riverpod: ^2.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_data_connect: ^0.1.2+5
  google_sign_in: ^6.2.2
  webview_flutter: ^4.10.0
  riverpod: ^2.6.1
  url_launcher: ^6.2.5
  firebase_storage: ^12.4.5
  connectivity_plus: ^6.1.4
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
