// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:drivepay/config/bundleID.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8mvemV3EwfBN9P_yl-XKctjS9eudLA0',
    appId: '1:998415778967:web:296ec531251fc0c10795d2',
    messagingSenderId: '998415778967',
    projectId: 'drivepay-0405',
    authDomain: 'drivepay-0405.firebaseapp.com',
    storageBucket: 'drivepay-0405.firebasestorage.app',
    measurementId: 'G-N90QLC0L2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKOzCvO5WivcEhnoMngS410fwzDpso2g',
    appId: '1:998415778967:android:fc3a28a309ca5e630795d2',
    messagingSenderId: '998415778967',
    projectId: 'drivepay-0405',
    storageBucket: 'drivepay-0405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7Cx8443UqayJJBXqBoQEsTT-KMsBw5o',
    appId: '1:998415778967:ios:56fe9da62c8d74e40795d2',
    messagingSenderId: '998415778967',
    projectId: 'drivepay-0405',
    storageBucket: 'drivepay-0405.firebasestorage.app',
    iosBundleId: '${Bundleid.ID}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7Cx8443UqayJJBXqBoQEsTT-KMsBw5o',
    appId: '1:998415778967:ios:318066f19a288b490795d2',
    messagingSenderId: '998415778967',
    projectId: 'drivepay-0405',
    storageBucket: 'drivepay-0405.firebasestorage.app',
    iosBundleId: 'com.example.drivepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8mvemV3EwfBN9P_yl-XKctjS9eudLA0',
    appId: '1:998415778967:web:b7e19451b7062a750795d2',
    messagingSenderId: '998415778967',
    projectId: 'drivepay-0405',
    authDomain: 'drivepay-0405.firebaseapp.com',
    storageBucket: 'drivepay-0405.firebasestorage.app',
    measurementId: 'G-W0W67GY1Y1',
  );
}
